language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "adeptj"
    token:
      secure: ${SONAR_TOKEN}

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package -P ApacheHttpClient,HibernateValidator,RESTEasy,Jackson,ReactiveStreams sonar:sonar -Dsonar.projectKey=adeptj-runtime

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'