language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "adeptj"
    token:
      secure: ${SONAR_TOKEN}

jdk:
  - openjdk11

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=adeptj-runtime

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

branches:
  only:
    - master