language: java
sudo: false
install: true
addons:
  sonarcloud:
    token:
      secure: ${SONAR_TOKEN}
  organization: "adeptj"

jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package -P Apache-HttpClient,RESTEasy,Jackson,MySQL,JDBC-CP-Hikari,JPA-EclipseLink,AWS sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'